name: Feature Branches Pipeline

on:
  push:
  #   branches: [124-create-a-pipeline-and-deploy-on-server] # remove later
    branches-ignore:
        - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3

  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm ci
        working-directory: frontend/react-app
      - run: npm run lint
        working-directory: frontend/react-app
